### ISSUE TITLE
Template placeholder parsing seems slightly off in 'Your driving test result on ...' email.

### ISSUE THREAD

**Issue by furnivall** [dvsa/cvs-tsk-cert-gov-notify#54]
Hi folks,

Sorry to bother you - I'm also a dev within a different branch of govt (HMCTS). 

By a lucky twist of fate, when I passed my test I spotted a telltale gov notify placeholder in the confirmation email:

![image](https://user-images.githubusercontent.com/18507008/186911157-35991da6-e7a7-4f30-b879-9cf07f2f9347.png)

I figured I should probably let someone know - this may not be the right repo for this, so I apologise if so. I would have made a PR but I guess your templates are probably not stored within github.

If I can provide any clarity on my personal info so this can be tracked, please feel free to contact me regarding this issue and I'll share whatever is desired :)

Thanks,

Danny

**Comment by matthew2564** [comment]
Hi, thanks for reporting.

I've forwarded this on to the appropriate team and it's confirmed to be rectified.
